/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-library-conventions")
}

dependencies {
    implementation(libs.jarkarta.rs.api)
    implementation(libs.jackson.databind)

    implementation(libs.immutables.annotations)
    annotationProcessor(libs.immutables.value)

    testImplementation(libs.bundles.testing)
    testImplementation(libs.codehead.test)
    testAnnotationProcessor(libs.immutables.value)
}

