/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-application-conventions")

    id("io.freefair.aspectj.post-compile-weaving") version "8.14.2" // Used for aspects
}

dependencies {
    implementation(project(":rules-engine-api"))
    implementation(project(":server-base"))
    implementation(libs.dropwizard.core)
    implementation(libs.commons.codec)
    testImplementation(libs.dropwizard.testing)

    implementation(libs.bundles.logging)
    implementation(libs.bundles.caffine)
    implementation(libs.bundles.drools)
    implementation(libs.aws.sdk.ddb)

    // PreCompile
    implementation(libs.javax.inject)
    implementation(libs.dagger)
    annotationProcessor(libs.dagger.compiler)
    implementation(libs.immutables.annotations)
    annotationProcessor(libs.immutables.value)
    testAnnotationProcessor(libs.dagger.compiler)
    testAnnotationProcessor(libs.immutables.value)

    // Metrics
    implementation(libs.micrometer.core)
    implementation(libs.codehead.metrics)
    implementation(libs.codehead.metrics.micrometer)
    implementation(libs.codehead.metrics.declarative)
    aspect(libs.codehead.metrics.declarative)
    testImplementation(libs.codehead.metrics.test)

    testImplementation(libs.bundles.logback)
    testImplementation(libs.bundles.testing)
    testImplementation(libs.codehead.test)
    testImplementation(libs.database.test)
    testImplementation(libs.aws.dynamodblocal)
    testImplementation(libs.bundles.log4j)
}

application {
    mainClass.set("com.codeheadsystems.rules.RulesEngineServer")
}
