@startuml

title Rule Domain Model

class RuleFile {}
class File {
    {field} path
}
class VelocityFiles {}
class RuleSet {}
class RuleSetIdentifier {}
class RuleIdentifier {}
class EventIdentifier {}
class Event {
  {field} timestamp
  {field} shadow
}
class Facts {}
class ExecutionResults {}
class Rule {}
class Velocity{
    {field} identifierPath
    {field} aggregationPath
    {field} window
}

EventIdentifier "1" -- "1" Event
Event *--> "1" Facts : contains
EventIdentifier -right->  ExecutionResults

ExecutionResults -right-> "1" RuleSetIdentifier
RuleSetIdentifier "1" -- "1" RuleSet

RuleSet o--> "*" Rule : contains
RuleSet o--> "*" Velocity : contains
Rule o-- RuleIdentifier : has
Rule o--> "*" RuleFile : contains
Velocity o--> "*" VelocityFiles : contains
File <|-- VelocityFiles
File <|-- RuleFile


@enduml