@startuml

class RuleFile {}
class File {
    {field} s3Bucket
    {field} path
}
class VelocityFiles {}
class RuleSet {}
class RuleSetIdentifier {}
class EventIdentifier {}
class Event {
  {field} timestamp
  {field} shadow
}
class Facts {}
class ExecutionResults {}
class Rule {}

File <|-up- VelocityFiles
File <|-up- RuleFile

RuleSet o-left- RuleSetIdentifier : has
RuleSet o--> "*" RuleFile : contains
RuleSet o--> "*" VelocityFiles : contains
Rule --right> RuleFile : contains
EventIdentifier --> "1" RuleSet
EventIdentifier "1" -right- "*" Event
Event *--> "1" Facts : contains
Event --> "1" ExecutionResults : produces

@enduml