package drl.tenant;

import com.codeheadsystems.rules.model.JsonObject;

global com.codeheadsystems.rules.model.RuleExecutionResult executionResult;
global java.lang.String eventId;

dialect  "mvel"

rule "There is a color"
    when
        // The following will call 'asString("/color")' twice due to the != null check
        JsonObject($a : asString("/color") != null)
    then
        System.out.println("Color found: ");
        executionResult.put("we found", $a);
end
